# Generated by Django 4.1.6 on 2023-02-15 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fotografia_id', models.IntegerField()),
                ('is_favorito', models.BooleanField()),
                ('data_like', models.DateTimeField(default=datetime.datetime(2023, 2, 15, 9, 28, 56, 95694))),
            ],
        ),
    ]
