# Generated by Django 4.1.6 on 2023-02-15 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_fotografia_data_fotografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 10, 34, 53, 180395)),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='fotografia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografia_id', to='galeria.fotografia'),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
