# Generated by Django 4.1.6 on 2023-02-15 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_alter_favoritos_data_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritos',
            name='fotografia_id',
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 24, 59, 762030)),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
