# Generated by Django 4.1.6 on 2023-02-15 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0017_fotografia_favoritos_id_and_more'),
        ('usuarios', '0007_alter_favoritos_data_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='fotografia_id',
            field=models.ForeignKey(default='tnc', on_delete=django.db.models.deletion.CASCADE, related_name='fotoid', to='galeria.fotografia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 42, 21, 235136)),
        ),
    ]
