# Generated by Django 4.1.6 on 2023-02-15 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_favoritos_data_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='fotografia_id',
            new_name='fotografia',
        ),
        migrations.RenameField(
            model_name='favoritos',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 46, 13, 477540)),
        ),
    ]
