# Generated by Django 4.1.6 on 2023-02-16 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_favoritos_data_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 44, 51, 822587)),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='fotografia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
