# Generated by Django 4.1.6 on 2023-02-16 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_favoritos_data_like_alter_favoritos_fotografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 46, 9, 648033)),
        ),
    ]
