# Generated by Django 4.1.6 on 2023-02-16 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0026_remove_fotografia_favorito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0016_alter_favoritos_data_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='data_like',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 58, 20, 116033)),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='fotografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotoid', to='galeria.fotografia'),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
