# Generated by Django 4.1.6 on 2023-02-15 14:31

import datetime
from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_favoritos_data_like'),
        ('galeria', '0014_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='favoritos',
            field=models.OneToOneField(default=0, on_delete=django.db.models.aggregates.Count, to='usuarios.favoritos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 31, 2, 951167)),
        ),
    ]
