# Generated by Django 4.1.6 on 2023-02-15 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_remove_fotografia_favoritos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='favoritos_id',
            field=models.CharField(default='tnc', max_length=3),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 42, 21, 234008)),
        ),
    ]
