# Generated by Django 4.1.6 on 2023-02-16 17:46

import datetime
from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_favoritos_data_like'),
        ('galeria', '0024_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='favorito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.aggregates.Count, related_name='fav', to='usuarios.favoritos'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 46, 9, 648612)),
        ),
    ]
