# Generated by Django 4.1.6 on 2023-02-16 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0025_fotografia_favorito_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='favorito',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 58, 20, 115118)),
        ),
    ]
