# Generated by Django 4.1.6 on 2023-02-16 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0026_remove_fotografia_favorito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 18, 59, 54, 954107)),
        ),
    ]
